# This is a config for E2B sandbox template.
# You can use template ID (32fvm6sb3pu2gr101vxu) or template name (create-staging-stable) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("create-staging-stable") # Sync sandbox
# sandbox = await AsyncSandbox.create("create-staging-stable") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('create-staging-stable')

template_id = "32fvm6sb3pu2gr101vxu"
dockerfile = "Dockerfile"
template_name = "create-staging-stable"
start_cmd = "/usr/local/bin/start-cmd.sh"
ready_cmd = "/usr/local/bin/ready-cmd.sh"
cpu_count = 4
memory_mb = 4_096
team_id = "83d3a3cc-12fc-4436-8e49-003f3de8a463"
